### ISSUE TITLE
Apple Books reader formatting glitch

### ISSUE THREAD

**Issue by cormullion** [laborg/DocumenterEpub.jl#1]
On MacOS (and iOS) there's a small problem with formatting code:

<img width="1336" alt="Screenshot 2021-01-18 at 10 23 56" src="https://user-images.githubusercontent.com/52289/104902943-49426380-5977-11eb-80db-50f21c2775fd.png">

The input lines  are picking up Georgia rather than a monospaced font.

(MacBooks version 2.4)

(Otherwise, this is awesome, thanks!)

**Comment by laborg** [comment]
I've added another metadata file necessary for macOS, please try this build:
https://github.com/laborg/DocumenterEpubExample/blob/master/The_Julia_Language_color_mac_v2.epub

**Comment by cormullion** [comment]
Looks great!

<img width="1016" alt="Screenshot 2021-01-18 at 13 25 21" src="https://user-images.githubusercontent.com/52289/104920998-9f6fd080-5990-11eb-813a-d0348068634f.png">

Thanks!

**Comment by laborg** [comment]
Thanks for the verification - I'll test if the added metadata creates problems on other e-readers (validation with `epubcheck` fails...) If not I'll add it to the new release.

**Comment by laborg** [comment]
Fixed in https://github.com/laborg/DocumenterEpub.jl/commit/969bfe40e658f776574b60aeb42c7edbdfd04229
