### ISSUE TITLE
Compatible with Documenter 0.27?

### ISSUE THREAD

**Issue by cormullion** [laborg/DocumenterEpub.jl#3]
Is this nice package compatible with Documenter 0.27?

**Comment by laborg** [comment]
Mhm... good question, but I don't know the answer. I wanted to update it when Julia 1.7 gets released, and at this point in time deal with a couple of other updates (your fonts, documenter 0.27...)

**Comment by cormullion** [comment]
Great, thanks!

**Comment by laborg** [comment]
Fixed in v0.2.0
